# Generated by Django 4.2.1 on 2023-07-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
    ]
