# Generated by Django 4.2.1 on 2023-07-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hackathon_participant',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
