# Generated by Django 4.2.1 on 2023-07-22 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_remove_profile_registered_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registered_activities',
            field=models.ManyToManyField(blank=True, related_name='registered_activities', to=settings.AUTH_USER_MODEL),
        ),
    ]
