# Generated by Django 4.2.1 on 2023-07-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_activity_registered_activities'),
        ('users', '0010_profile_registered_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registered_activities',
            field=models.ManyToManyField(blank=True, related_name='registered_activities', to='base.activity'),
        ),
    ]
