# Generated by Django 4.2.1 on 2023-07-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_project_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='featured_image',
            field=models.ImageField(blank=True, default='default_pic.jpeg', null=True, upload_to=''),
        ),
    ]
