# Generated by Django 4.2.1 on 2023-07-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_activity_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
