# Generated by Django 4.2.1 on 2023-07-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_activity_vote_ratio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='activity',
            name='featured_image',
            field=models.ImageField(blank=True, default='default1.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='activity',
            name='vote_ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
