# Generated by Django 4.2.1 on 2023-07-18 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_activity_user_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='user_tags',
        ),
        migrations.AddField(
            model_name='activity',
            name='scheduled_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
