# Generated by Django 4.2.1 on 2023-07-18 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0013_remove_activity_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='signed_up_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
