# Generated by Django 4.2.1 on 2023-07-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_activity_signed_up_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='scheduled_time',
            new_name='scheduled_date',
        ),
    ]
