# Generated by Django 4.2.1 on 2023-07-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_scheduled_time_activity_scheduled_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='signed_up_users',
        ),
    ]
