# Generated by Django 4.2.1 on 2023-07-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_activity_joined_users_activity_signed_up_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='joined_users',
        ),
    ]
