# Generated by Django 4.2.1 on 2023-07-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_registered_activities'),
        ('base', '0019_remove_activity_signed_up_users_activity_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='registered_activities',
            field=models.ManyToManyField(blank=True, related_name='registered_users', to='users.profile'),
        ),
    ]
