# Generated by Django 4.2.1 on 2023-07-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_activity_registered_activities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='registered_activities',
        ),
    ]
